**Install library untuk scraping data**

In [ ]:
!pip install google-play-scraper # https://github.com/JoMingyu/google-play-scraper

Collecting google-play-scraper
  Downloading google-play-scraper-1.0.5.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 1.2 MB/s
Building wheels for collected packages: google-play-scraper
  Building wheel for google-play-scraper (setup.py) ... done
  Created wheel for google-play-scraper: filename=google_play_scraper-1.0.5-py3-none-any.whl size=24484 sha256=beb66b877652366a7ee4409173ea090825239d31de001fbeae38c55f8ddeee8d
  Stored in directory: /root/.cache/pip/wheels/4a/26/18/48fda51f20c9e550c735fa6f3a6887dc8836f8d709a3cf8a9c
Successfully built google-play-scraper
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.0.5

**Import library yang telah kita install bersama dengan beberapa library tambahan**

In [ ]:
import pandas as pd # library untuk mengubah hasil scraping menjadi dataframe dan mengelola dataframe
from tqdm import tqdm # library untuk menampilkan progress bar pada proses scraping

from google_play_scraper import Sort, reviews, app # library untuk scraping data

**Definisikan App ID dan masukkan ke dalam function untuk scraping data**

In [ ]:
# mendefinisikan App ID dan variabel hasil scraping data
app_id = ['com.telkomsel.telkomselcm']
app_reviews = []

# function untuk scraping data berada di dalam perulangan For dengan beberapa kondisi tertentu
for app in tqdm(app_id):
  for score in list(range(1, 6)):
    for sort_order in [Sort.MOST_RELEVANT, Sort.NEWEST]:
      # scraping data ulasan per pengguna
      rvs, _ = reviews(
        app,
        lang = 'id',
        country = 'id',
        sort = sort_order,
        count= 500 if score == 3 else 500,
        filter_score_with = score
      )
      # menggabungkan hasil scraping ulasan per pengguna menjadi satu hasil dalam bentuk List
      for r in rvs:
        r['sortOrder'] = 'most_relevant' if sort_order == Sort.MOST_RELEVANT else 'newest'
        r['appId'] = app
      app_reviews.extend(rvs)

100%|██████████| 1/1 [00:09<00:00,  9.25s/it]

**Hitung jumlah ulasan yang kita peroleh dari hasil scraping**

In [ ]:
len(app_reviews) # Karena ada batasan dari library "google-play-scraper", sehingga kita tidak dapat scraping seluruh hasil ulasan pengguna

5000

In [ ]:
print(type(app_reviews))

<class 'list'>

**Konversi hasil scraping data menjadi dataframe**

In [ ]:
df = pd.DataFrame(app_reviews)
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,sortOrder,appId
0,gp:AOqpTOGS4Es_EKX7MUoBBrZme8unggOA9rojT23fAh2...,Mursid W. Hananto,https://play-lh.googleusercontent.com/a-/AOh14...,"Aplikasi payah. Kalo melakukan daily check-in,...",1,1593,6.10.0-9,2022-04-28 08:00:29,"Hai, Kak Mursid. Maaf ya. Mengenai keluhan Dai...",2022-04-28 08:11:00,most_relevant,com.telkomsel.telkomselcm
1,gp:AOqpTOFg4ujPiOo7Sz8tqvF-PuQXu63kVMneDrKgyxy...,Dwi Hernanda,https://play-lh.googleusercontent.com/a/AATXAJ...,Rekomendasi paket data tidak sesuai dgn kebutu...,1,1544,6.10.0-9,2022-04-26 03:20:48,"Halo, Kak Dwi. Maaf jadi ga nyaman. Aplikasi M...",2022-04-26 06:21:47,most_relevant,com.telkomsel.telkomselcm
2,gp:AOqpTOEJb8dMqLvnKSE3XZsqprKcdBMOqR9KumxbZya...,Jimmy MSP,https://play-lh.googleusercontent.com/a/AATXAJ...,Makin kesini makin mahal paketnya. Makin kesin...,1,41,6.10.0-9,2022-05-16 03:30:50,"Maaf ya, Kak Jimmy. Terkait keluhan tarif pake...",2022-05-16 03:37:03,most_relevant,com.telkomsel.telkomselcm
3,gp:AOqpTOFSZipRaI12fDcPQQNyoTdzHsQVsO7ftRuqCWk...,Arif Rahman Hakim,https://play-lh.googleusercontent.com/a-/AOh14...,"Gabisa masuk aplikasi, keterangan 'Oops terjad...",1,1990,6.9.1,2022-04-15 02:13:04,"Halo, Kak Arif. Maaf atas kendala akses data l...",2022-04-15 02:46:36,most_relevant,com.telkomsel.telkomselcm
4,gp:AOqpTOH34AQWvPm4do5eoc7O-CHHlnBwRsCSoeC_9Nk...,Budiono Asmoro,https://play-lh.googleusercontent.com/a-/AOh14...,1. Pembayaran pembelian pulsa/paket data lewat...,1,901,6.9.1,2022-04-16 04:27:30,"Maaf ya, Kak Budiono. Jika ada pertanyaan atau...",2021-07-26 23:52:22,most_relevant,com.telkomsel.telkomselcm
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,gp:AOqpTOGILtJzmYgZXMf6zlM3imB6absm9XIcfw-VfNm...,C gunawan,https://play-lh.googleusercontent.com/a-/AOh14...,"bagus, sangat bermanfaat",5,0,6.10.0-9,2022-05-20 02:06:35,None,NaT,newest,com.telkomsel.telkomselcm
4996,gp:AOqpTOFr_AwC0hoBIN8EshfcEtI93cjJGb2LvGU2Ov9...,HIRONIMUS ATOK,https://play-lh.googleusercontent.com/a-/AOh14...,mantap,5,0,6.10.0-9,2022-05-20 02:05:07,None,NaT,newest,com.telkomsel.telkomselcm
4997,gp:AOqpTOHdPVSVFAOWZ2lN5BzvRiC4qiQTnhUTxr140Ak...,Aswan Odhe,https://play-lh.googleusercontent.com/a/AATXAJ...,bagus,5,0,6.10.0-9,2022-05-20 02:04:43,None,NaT,newest,com.telkomsel.telkomselcm
4998,gp:AOqpTOH8pQW2J296A54GK0XjKFh3cf53ls-6pzyGr9u...,Imam Mukhlas,https://play-lh.googleusercontent.com/a/AATXAJ...,sangat membantu,5,0,6.10.0-9,2022-05-20 02:00:27,None,NaT,newest,com.telkomsel.telkomselcm
4999,gp:AOqpTOGCNv7rvj5RSHcwXOfYyEm-Em-wc7b2hXwvKv-...,Patar Junaidi Bm,https://play-lh.googleusercontent.com/a-/AOh14...,Bagus Selalu beli paket dan buat undian tapi b...,5,0,None,2022-05-20 01:55:28,None,NaT,newest,com.telkomsel.telkomselcm

In [ ]:
df['score'].value_counts()

1    1000
2    1000
3    1000
4    1000
5    1000
Name: score, dtype: int64

**Hapus ulasan dengan rating 3 bintang agar dataset balanced**

In [ ]:
df.drop(df.loc[df['score']==3].index, inplace=True)
len(df)

4000

**Hapus kolom yang tidak digunakan**

In [ ]:
df.drop(['reviewId', 'userImage', 'userName', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt','sortOrder','appId'], axis=1, inplace=True)

In [ ]:
pd.options.display.max_colwidth=1000
df.head()

,content,score
0,"Aplikasi payah. Kalo melakukan daily check-in, harus ditunggu dulu bbrp lama baru bisa dilihat hasil check-in, kalo terlalu cepat masuk pasti error. Ini aplikasi tak bisa menunggu proses di server, kalo merequest saat server masih proses check-in selalu error. Diminta cek bug malah yg ditanya data pribadi (yg sdh ada di sana). Utk apa validasi krn yg sy minta adlh cek aps mereka thdp bug. Dikiranya sdh sempurna tanpa bug.",1
1,"Rekomendasi paket data tidak sesuai dgn kebutuhan !!!! Tidak ada yg sesuai dgn kebutuhan daftar paket data!!! Ada fitur filter, ternyata hanya memfilter di bagian rekomendasi saja yg hasilnya sama... Fitur rekomendasi sangat tidak berguna!!! Memaksa pelanggan membeli paket yg tidak sesuai?? Beralih menjadi pelanggan sblh lebih baik... Bangkrut saja sana!!",1
2,Makin kesini makin mahal paketnya. Makin kesini makin jelek sinyalnya. Kdang sinyal hilang. Dan tiap nomor paketnya beda² ada yg murah dan juga ada yg 2x lipat pembayaranya (tidak sama rata),1
3,"Gabisa masuk aplikasi, keterangan 'Oops terjadi kesalahan.' Paket makin kesini makin mahal tp pelayanan makin buruk, speed up-down, lelet, kadang sinyal ilang, gabisa connect, bar sinyal full 4g+ tp lelet bgt. Kalo terusan begini, pasti kelihalangan banyak pelanggan setia. Tolong dipertimbangin :)",1
4,"1. Pembayaran pembelian pulsa/paket data lewat aplikasi dipermudah pakai Virtual Account bank2 dalam negri karena INDOSAT saja sudah bisa, masa TELKOMSEL kalah ??? 2. Kenapa harus ada perbedaan menu paket data setiap pelanggan, kalau dibeda2kan mending seperti dulu lagi ada simpati, as, dll sehingga pelanggan yg tidak mampu bisa menyesuaikan karena as sdh dikenal murah harga paket datanya. Kl seperti sekarang sama saja Telkomsel pasang jebakan utk mendapatkan pemasukan yg besar.",1

In [ ]:
label = {
    1 : 'negatif',
    2 : 'negatif',
    4 : 'positif',
    5 : 'positif' 
}

In [ ]:
sentiment = df["score"].replace(label)

In [ ]:
df.drop(['content'], axis=1, inplace=True)
df

      score
0         1
1         1
2         1
3         1
4         1
...     ...
4995      5
4996      5
4997      5
4998      5
4999      5

[4000 rows x 1 columns]

In [ ]:
df['score'] = score
df

      score
0         5
1         5
2         5
3         5
4         5
...     ...
4995      5
4996      5
4997      5
4998      5
4999      5

[4000 rows x 1 columns]

**Konversi dataframe menjadi bentuk CSV**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df.to_csv("/content/drive/MyDrive/KP_2022/dataset/raw_dataset.csv", index=None)

**Download file CSV**

In [ ]:
import pandas as pd

data = pd.read_csv("/content/DATASE~1.CSV")
data

,Unnamed: 0,text,score,sentiment
0,1,abdat buka aplikasi respon,0,Positif
1,2,admin langsung laku terima kasih aplikasikasih bintang kembang,2,Positif
2,3,adminkasih solusi nomor tlpn daftarindaftarmobilepakai nomor,3,Positif
3,4,aflikasi batu banget,1,Positif
4,5,ajuk daya bangetstandar butuh,0,Positif
...,...,...,...,...
1513,1514,vrifikasi akun,0,Positif
1514,1515,wilayah jateng layan pasang mobaile,0,Positif
1515,1516,wooooww keren,1,Positif
1516,1517,yakurang simple cepat respon,1,Positif
1517,1518,yuyun yuhaeni alami sulit masuklistrik harga ribu daya,1,Positif